baseurl = "http://routespcl.github.io"
title = "Route's website"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

[params]
  arthor = "Route"
  info = "Gaming | Music | Computer"
  description = "Route's personal webpage"
  keywords = "blog, music, game, computer"
  avatarurl = "images/avatar.jpg"

  since = 2022

  enableTwemoji = true

  colorScheme = "dark"
  hidecolorschemetoggle = false

  customCSS = ["css/custom-font.css"]
  customSCSS = []
  customJS = []

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/routespcl/"

[[params.social]]
name = "Twitter"
icon = "fa fa-2x fa-twitter"
weight = 3
url = "https://twitter.com/Route_spcl/"

[[languages.en.menu.main]]
name = "About me"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Projects"
weight = 3
url = "projects/"
